services:
  axum_file_management_service:
    container_name: axum_file_management_service
    image: amsatrio/axum_file_management_service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile.debian
    ports:
      - "8003:8003"
    #network_mode: "host"
    networks:
      - sql-database
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      replicas: 1
    volumes:
      - /root/.cargo:/root/.cargo
      - /root/.m2:/root/.m2

networks:
  sql-database:
    name: sql-database-network
    external: true
