apiVersion: v1
kind: PersistentVolume
metadata:
  name: axum-file-management-pv
spec: 
  capacity:
    storage: 10Gi
  accessModes:
   - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/sdb"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: axum-file-management-pvc
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

