services:
  axum_file_management_service:
    container_name: axum_file_management_service
    image: amsatrio/axum_file_management_service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    #network_mode: "host"
    networks:
      - sql-database
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      replicas: 1

networks:
  sql-database:
    name: sql-database-network
    external: true
