services:
  app:
    container_name: axum-file-management-service
    image: axum-file-management-service
    build:
      context: ../../
      dockerfile: Dockerfile.debian
    ports:
      - "8003:8003"
    networks:
      - sql-database
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      replicas: 1

networks:
  sql-database:
    name: sql-database-network
    external: true
